# -*- coding: utf-8 -*-
"""Lab7PMP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-EUcYlcCtuLoRBg1RKXx-F-OwSdAhijs

# **Laboratorul 7 PMP**

## **Exercitiul 1**
"""

import numpy as np
import pymc as pm
import arviz as az
import matplotlib.pyplot as plt

# a)

data = np.array([56, 60, 58, 55, 57, 59, 61, 56, 58, 60])

x_bar = data.mean()
print("x (sample mean) =", x_bar)

with pm.Model() as model:
    mu = pm.Normal("mu", mu=x_bar, sigma=10)
    sigma = pm.HalfNormal("sigma", sigma=10)
    y = pm.Normal("y", mu=mu, sigma=sigma, observed=data)

    trace = pm.sample(2000, tune=2000, target_accept=0.9, random_seed=42)

# b)

summary = az.summary(trace, var_names=["mu", "sigma"], hdi_prob=0.95)
print("\nPosterior summaries (95% HDI):")
print(summary)

az.plot_posterior(trace, var_names=["mu", "sigma"], hdi_prob=0.95)
plt.suptitle("Posterior distributions for μ and σ (95% HDI)", fontsize=12)
plt.show()

# c)

freq_mean = data.mean()
freq_sd = data.std(ddof=1)
print("\nFrequentist estimates:")
print(f"Sample mean = {freq_mean:.3f}")
print(f"Sample std (ddof=1) = {freq_sd:.3f}")