# -*- coding: utf-8 -*-
"""Lab14PMP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oSCfR6goNU5ZWP40XtwU2I6kP4LjuZYm

# **Laboratorul 14 PMP**
"""

import numpy as np
import pandas as pd
import pymc as pm
import arviz as az
import matplotlib.pyplot as plt

az.style.use("arviz-darkgrid")

from google.colab import files
files.upload()

import re

path = "date_colesterol.csv"

try:
    df = pd.read_csv(path, sep=",", encoding="utf-8-sig")
except Exception:
    df = pd.read_csv(path, header=0, encoding="utf-8-sig")

if df.shape[1] == 1:
    col0 = df.columns[0]
    split = df[col0].astype(str).str.split(r"[;,]", expand=True)
    df = split.iloc[:, :2].copy()
    df.columns = ["Ore_Exercitii", "Colesterol"]
else:
    df.columns = [re.sub(r'["\']', "", str(c)).strip() for c in df.columns]
    df = df.iloc[:, :2].copy()
    df.columns = ["Ore_Exercitii", "Colesterol"]

for c in ["Ore_Exercitii", "Colesterol"]:
    df[c] = df[c].astype(str).str.replace(",", ".", regex=False).str.strip()
    df[c] = pd.to_numeric(df[c], errors="coerce")

df = df.dropna().reset_index(drop=True)

x_raw = df["Ore_Exercitii"].to_numpy(dtype=float)
y_raw = df["Colesterol"].to_numpy(dtype=float)

x = (x_raw - x_raw.mean()) / x_raw.std()
y = (y_raw - y_raw.mean()) / y_raw.std()
x2 = x**2

def fit_mixture_poly(K, draws=1200, tune=2000, target_accept=0.99, seed=42):
    """
    y_i ~ sum_k w_k * Normal(mu_{k,i}, sigma_k)
    mu_{k,i} = alpha_k + beta_k * x_i + gamma_k * x_i^2
    """
    with pm.Model() as model:
        w = pm.Dirichlet("w", a=np.ones(K))

        alpha = pm.Normal("alpha", 0.0, 1.0, shape=K)
        beta  = pm.Normal("beta",  0.0, 1.0, shape=K)
        gamma = pm.Normal("gamma", 0.0, 1.0, shape=K)

        sigma = pm.HalfNormal("sigma", 1.0, shape=K)

        mu_nk = (alpha[None, :] + beta[None, :]*x[:, None] + gamma[None, :]*x2[:, None])

        pm.NormalMixture("y_obs", w=w, mu=mu_nk, sigma=sigma, observed=y)

        idata = pm.sample(
            draws=draws,
            tune=tune,
            chains=4, cores=4,
            target_accept=target_accept,
            init="jitter+adapt_diag",
            nuts={"max_treedepth": 15},
            random_seed=seed,
            return_inferencedata=True
        )

    return model, idata

Ks = [3, 4, 5]
models = {}
idatas = {}

for K in Ks:
    print(f"\n--- Fitting K={K} ---")
    model, idata = fit_mixture_poly(K, draws=1200, tune=2000, target_accept=0.99, seed=42)
    models[K] = model
    idatas[K] = idata

for K in Ks:
    print(f"\n=== K={K} summary (95% HDI) ===")
    display(
        az.summary(
            idatas[K],
            var_names=["w", "alpha", "beta", "gamma", "sigma"],
            hdi_prob=0.95
        )
    )

for K in Ks:
    pm.compute_log_likelihood(idatas[K], model=models[K])

idata_dict = {f"K={K}": idatas[K] for K in Ks}

cmp_waic = az.compare(idata_dict, ic="waic", method="BB-pseudo-BMA", scale="deviance")
cmp_loo  = az.compare(idata_dict, ic="loo",  method="BB-pseudo-BMA", scale="deviance")

print("=== WAIC (deviance) — mai mic = mai bun ===")
display(cmp_waic)
az.plot_compare(cmp_waic)
plt.title("Model comparison (WAIC, deviance)")
plt.show()

print("=== LOO (deviance) — mai mic = mai bun ===")
display(cmp_loo)
az.plot_compare(cmp_loo)
plt.title("Model comparison (LOO, deviance)")
plt.show()

print("Best by WAIC:", cmp_waic.index[0])
print("Best by LOO :", cmp_loo.index[0])

best_key = cmp_waic.index[0]
best_K = int(best_key.split("=")[1])
post = idatas[best_K].posterior.stack(sample=("chain","draw"))

w_m = post["w"].mean("sample").values
a_m = post["alpha"].mean("sample").values
b_m = post["beta"].mean("sample").values
g_m = post["gamma"].mean("sample").values

xg = np.linspace(x.min(), x.max(), 250)
xg2 = xg**2

plt.figure(figsize=(8,5))
plt.scatter(x, y, s=10, label="data (std)")

for k in range(best_K):
    yg = a_m[k] + b_m[k]*xg + g_m[k]*xg2
    plt.plot(xg, yg, label=f"comp {k+1} (w≈{w_m[k]:.2f})")

plt.title(f"Mixture quadratic regression — {best_key}")
plt.xlabel("Ore exercitii (std)")
plt.ylabel("Colesterol (std)")
plt.legend()
plt.show()