# -*- coding: utf-8 -*-
"""Lab11PMP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18xfoeLuT_e6XcRfRfpH8jvlbEXLYB7ao

# **Laboratorul 11 PMP**
"""

!pip -q install pymc arviz numpy pandas

import numpy as np
import pandas as pd
import pymc as pm
import arviz as az
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("Prices.csv")

y = df["Price"].astype(float).values
x1 = df["Speed"].astype(float).values
x2 = np.log(df["HardDrive"].astype(float).values)

x1_mean = x1.mean()
x2_mean = x2.mean()
x1_c = x1 - x1_mean
x2_c = x2 - x2_mean

"""## **a)**"""

with pm.Model() as model_basic:
    x1_shared = pm.Data("x1_shared", x1_c)
    x2_shared = pm.Data("x2_shared", x2_c)

    alpha = pm.Normal("alpha", mu=0, sigma=10)
    beta1 = pm.Normal("beta1", mu=0, sigma=10)
    beta2 = pm.Normal("beta2", mu=0, sigma=10)
    sigma = pm.HalfCauchy("sigma", beta=5)

    mu = pm.Deterministic("mu", alpha + beta1 * x1_shared + beta2 * x2_shared)
    y_obs = pm.Normal("y_obs", mu=mu, sigma=sigma, observed=y)

    idata_basic = pm.sample(draws=2000, tune=2000, chains=2, target_accept=0.9, random_seed=42)

az.plot_trace(idata_basic, var_names=["alpha", "beta1", "beta2", "sigma"])
plt.show()

"""## **b)**"""

summary_95 = az.summary(idata_basic, var_names=["beta1","beta2"], hdi_prob=0.95)
summary_95

"""## **c)**"""

def hdi_excludes_zero_from_summary(idata, var, hdi_prob=0.95):
    s = az.summary(idata, var_names=[var], hdi_prob=hdi_prob)
    low  = float(s.loc[var, f"hdi_{(1-hdi_prob)/2*100:.1f}%"])
    high = float(s.loc[var, f"hdi_{(1+(hdi_prob))/2*100:.1f}%"])
    excludes = (high < 0) or (low > 0)
    return excludes, (low, high), s

b1_ok, b1_hdi, _ = hdi_excludes_zero_from_summary(idata_basic, "beta1", 0.95)
b2_ok, b2_hdi, _ = hdi_excludes_zero_from_summary(idata_basic, "beta2", 0.95)

print("beta1 95% HDI:", b1_hdi, "=> util?", b1_ok)
print("beta2 95% HDI:", b2_hdi, "=> util?", b2_ok)

"""## **d)**"""

x1_new = 33.0
x2_new = np.log(540.0)

x1_new_c = x1_new - x1_mean
x2_new_c = x2_new - x2_mean

with model_basic:
    pm.set_data({"x1_shared": np.array([x1_new_c]),
                 "x2_shared": np.array([x2_new_c])})

    post = idata_basic.posterior.stack(sample=("chain","draw"))
    mu_new = (post["alpha"] + post["beta1"]*x1_new_c + post["beta2"]*x2_new_c).values

mu_new_hdi90 = az.hdi(mu_new, hdi_prob=0.90)
mu_new.mean(), mu_new_hdi90

"""## **e)**"""

with pm.Model() as model_pred:
    x1_shared = pm.Data("x1_shared", x1_c)
    x2_shared = pm.Data("x2_shared", x2_c)

    alpha = pm.Normal("alpha", mu=0, sigma=10)
    beta1 = pm.Normal("beta1", mu=0, sigma=10)
    beta2 = pm.Normal("beta2", mu=0, sigma=10)
    sigma = pm.HalfCauchy("sigma", beta=5)

    mu = alpha + beta1 * x1_shared + beta2 * x2_shared

    y_obs = pm.Normal("y_obs", mu=mu, sigma=sigma, observed=y)

    y_new = pm.Normal("y_new", mu=mu, sigma=sigma)

    idata_pred = pm.sample(
        draws=2000, tune=2000,
        chains=2, target_accept=0.9,
        random_seed=42
    )

with model_pred:
    pm.set_data({
        "x1_shared": np.array([x1_new_c]),
        "x2_shared": np.array([x2_new_c])
    })

    ppc = pm.sample_posterior_predictive(
        idata_pred,
        var_names=["y_new"],
        random_seed=42
    )

y_new_draws = ppc.posterior_predictive["y_new"].stack(sample=("chain","draw")).values
pred_hdi90 = az.hdi(y_new_draws, hdi_prob=0.90)

print("E[y_new | x] ~", float(np.mean(y_new_draws)))
print("90% HDI prediction interval:", pred_hdi90)