# -*- coding: utf-8 -*-
"""Partial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ce6S2MITSvw2baxi_bt-xBR8T_4t337M

# **Partial Examen PMP**

## **Subject 1**
"""

from pgmpy.models import BayesianNetwork
from pgmpy.factors.discrete import TabularCPD
from pgmpy.inference import VariableElimination
import networkx as nx

model = BayesianNetwork([('O', 'H'),('O', 'W'),('H', 'R'),('W', 'R'),('H', 'E'),('R', 'C')])

cpd_O = TabularCPD(variable='O', variable_card=2, values=[[0.3], [0.7]])
cpd_H = TabularCPD(variable='H', variable_card=2, values=[[0.9, 0.2], [0.1, 0.8]], evidence=['O'], evidence_card=[2])
cpd_W = TabularCPD(variable='W', variable_card=2, values=[[0.1, 0.6], [0.9, 0.4]] ,evidence=['O'], evidence_card=[2])
cpd_R = TabularCPD(variable='R', variable_card=2, values=[[0.6, 0.9, 0.3, 0.5], [0.4, 0.1, 0.7, 0.5]], evidence=['H', 'W'], evidence_card=[2, 2])
cpd_E = TabularCPD(variable='E', variable_card=2, values=[[0.8, 0.2], [0.2, 0.8]], evidence=['H'], evidence_card=[2])
cpd_C = TabularCPD(variable='C', variable_card=2, values=[[0.85, 0.40], [0.15, 0.60]], evidence=['R'], evidence_card=[2])

model.add_cpds(cpd_O, cpd_H, cpd_W, cpd_R, cpd_E, cpd_C)
assert model.check_model()

pos = nx.circular_layout(model)
nx.draw(model, with_labels=True, pos=pos, alpha=0.5, node_size=2000)

infer = VariableElimination(model)

H_given_C = infer.query(['H'], evidence={'C':0})
print(H_given_C)

E_given_C = infer.query(['E'], evidence={'C':0})
print(E_given_C)

HW_given_C = infer.query(['H','W'], evidence={'C':0})
print(HW_given_C)